name: Publish Development Release

on:
  push:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: assuo
            asset_name: assuo-linux
          - os: windows-latest
            artifact_name: assuo.exe
            asset_name: assuo-windows
          - os: macos-latest
            artifact_name: assuo
            asset_name: assuo-macos

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Publish release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: latest-dev
        body: "binary from main, CI/CD triggered"
        overwrite: true
        prerelease: true
